version: '3.8'

services:
  tasksdb:
    image: mongo
    container_name: tasksdb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - tasksdb-data:/data/db
    networks:
      - tasks_network
   

networks:
  tasks_network:

volumes:
  tasksdb-data:
